namespace oed_testdata.Server.Infrastructure.TestdataStore.Estate;

//**************** Generated from oed-events\src\Domstol.Hendelser.ApiClient\Spec\external_api.yaml ****************

//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------



#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"


[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public enum LovisaPartRole
{
    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"PART_ANNEN")]
    PART_ANNEN = 0,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"GJENLEV_EKTEFELLE_PARTNER")]
    GJENLEV_EKTEFELLE_PARTNER = 1,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"GJENLEV_PARTNER")]
    GJENLEV_PARTNER = 2,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"GJENLEV_SAMBOER")]
    GJENLEV_SAMBOER = 3,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"BARN")]
    BARN = 4,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"BARNEBARN")]
    BARNEBARN = 5,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SAERKULLSBARN")]
    SAERKULLSBARN = 6,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SAERKULLSBARN_BARN")]
    SAERKULLSBARN_BARN = 7,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FAR")]
    FAR = 8,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"MOR")]
    MOR = 9,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SOESKEN")]
    SOESKEN = 10,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SOESKENS_BARN")]
    SOESKENS_BARN = 11,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SOESKENS_BARNEBARN")]
    SOESKENS_BARNEBARN = 12,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"HALV_SOESKEN")]
    HALV_SOESKEN = 13,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"HALV_SOESKENS_BARN")]
    HALV_SOESKENS_BARN = 14,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FARFAR")]
    FARFAR = 15,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FARMOR")]
    FARMOR = 16,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"MORFAR")]
    MORFAR = 17,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"MORMOR")]
    MORMOR = 18,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"ONKEL")]
    ONKEL = 19,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"TANTE")]
    TANTE = 20,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FETTER")]
    FETTER = 21,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"KUSINE")]
    KUSINE = 22,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"STATEN")]
    STATEN = 23,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"AVDOEDE")]
    AVDOEDE = 24,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FORDRINGSHAVER")]
    FORDRINGSHAVER = 25,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"AVDOEDE_EKTEFELLE_PARTNER")]
    AVDOEDE_EKTEFELLE_PARTNER = 26,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"TEST_ARVING_FULL")]
    TEST_ARVING_FULL = 27,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"TEST_ARVING_BEGR")]
    TEST_ARVING_BEGR = 28,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"VERGE")]
    VERGE = 29,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FORELDREVERGE_AKTOER")]
    FORELDREVERGE_AKTOER = 30,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"MIDLERTIDIGVERGE_AKTOER")]
    MIDLERTIDIGVERGE_AKTOER = 31,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FULLMEKTIG")]
    FULLMEKTIG = 32,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"PROSFULL")]
    PROSFULL = 33,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"FREMTIDSFULLMEKTIG")]
    FREMTIDSFULLMEKTIG = 34,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"GJENLEV_EKTEFELLE")]
    GJENLEV_EKTEFELLE = 35,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"MOTTAKER_FULLMAKT_DOEDSBO_LITEN_VERDI")]
    MOTTAKER_FULLMAKT_DOEDSBO_LITEN_VERDI = 36,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"BARNEBARNS_BARN")]
    BARNEBARNS_BARN = 37,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"SOESKENS_BARNEBARNS_BARN")]
    SOESKENS_BARNEBARNS_BARN = 38,

    [System.Text.Json.Serialization.JsonStringEnumMemberName(@"HALV_SOESKENS_BARNEBARN")]
    HALV_SOESKENS_BARNEBARN = 39,

}

[System.Text.Json.Serialization.JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[System.Text.Json.Serialization.JsonDerivedType(typeof(PersonPart), typeDiscriminator: "Person")]
[System.Text.Json.Serialization.JsonDerivedType(typeof(PersonPappPart), typeDiscriminator: "PersonPapp")]
[System.Text.Json.Serialization.JsonDerivedType(typeof(ForetakPart), typeDiscriminator: "Foretak")]
[System.Text.Json.Serialization.JsonDerivedType(typeof(ForetakPappPart), typeDiscriminator: "ForetakPapp")]
[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class Part
{
    [System.Text.Json.Serialization.JsonPropertyName("role")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<LovisaPartRole>))]
    public LovisaPartRole Role { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("mottakerOriginalSkifteattest")]
    public bool MottakerOriginalSkifteattest { get; set; }

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class PersonPart : Part
{
    [System.Text.Json.Serialization.JsonPropertyName("nin")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.RegularExpression(@"^\d{11}$")]
    public string Nin { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("signertDato")]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset? SignertDato { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("formuesfullmakt")]
    public bool Formuesfullmakt { get; set; } = false;
}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class PersonPappPart : Part
{

    [System.Text.Json.Serialization.JsonPropertyName("navn")]
    [System.ComponentModel.DataAnnotations.Required]
    public PersonName Navn { get; set; } = new PersonName();

    [System.Text.Json.Serialization.JsonPropertyName("dateOfBirth")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
    public System.DateTimeOffset DateOfBirth { get; set; }

}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class ForetakPart : Part
{
    [System.Text.Json.Serialization.JsonPropertyName("organisasjonsNummer")]
    public string OrganisasjonsNummer { get; set; }
}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
public partial class ForetakPappPart : Part
{

    [System.Text.Json.Serialization.JsonPropertyName("organisasjonsNavn")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string OrganisasjonsNavn { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("registreringsNummer")]
    public string RegistreringsNummer { get; set; }

    /// <summary>
    /// ISO Country Code Alpha_3
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("countryCode")]
    public string CountryCode { get; set; }
}

public partial class PersonName
{
    [System.Text.Json.Serialization.JsonPropertyName("lastName")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string LastName { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("firstName")]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string FirstName { get; set; }

    [System.Text.Json.Serialization.JsonPropertyName("middleName")]
    public System.Collections.Generic.ICollection<string> MiddleName { get; set; }

    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    [System.Text.Json.Serialization.JsonExtensionData]
    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    {
        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
        set { _additionalProperties = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTimeOffset>
{
    public override System.DateTimeOffset Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
    {
        var dateTime = reader.GetString();
        if (dateTime == null)
        {
            throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
        }

        return System.DateTimeOffset.Parse(dateTime);
    }

    public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTimeOffset value, System.Text.Json.JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
    }
}

#pragma warning restore 649
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring as nullable.
