name: CI/CD testapp-app

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DOTNET_VERSION: '9.x' # Global environment variables
  TEST_APP_SERVICE_NAME: 'oed-testapp-app'
  PROD_RESOURCE_GROUP_NAME: 'altinn-digdir-oed-rg'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: GitHub metadata
      run: |
          printf "%s on %s by %s\n" "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" "$GITHUB_ACTOR"

    - name: Set up .NET
      uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release

    - name: Run Tests
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Publish
      run: mkdir -p /home/runner/.aspnet/https && dotnet publish ./src/oed-testdata.Server/oed-testdata.Server.csproj --no-build -c Release -o ./publish

    - name: Deploy to Azure App Service (Test)
      uses: azure/webapps-deploy@122b7ec46017e53a3f71e3a027d67550a1641f5e # v2
      with:
        app-name: '${{ env.TEST_APP_SERVICE_NAME}}'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: ./publish/